version: '2'
services:
    orguesaintmaxime-app:
        image: orguesaintmaxime
        external_links:
            - orguesaintmaxime-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/orguesaintmaxime
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    orguesaintmaxime-postgresql:
        extends:
            file: postgresql.yml
            service: orguesaintmaxime-postgresql
